name: CI

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - run: pip install tox
    - run: make lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.3.1
      with:
        minikube version: 'v1.24.0'
        kubernetes version: 'v1.22.3'
    - name: Interact with the cluster
      run: |
        export KUBECONFIG=$KUBECONFIG:$HOME/.kube/config
        kubectl cluster-info
        ls -la ~/.kube
        cat ~/.kube/config
      env:
        CHANGE_MINIKUBE_NONE_USER: true
